name: MacOS Builds
on: [push, pull_request]

# Global Cache Settings
env:
  SCONS_CACHE_LIMIT: 8192

jobs:
  macos-editor:
    runs-on: "macos-latest"

    name: Editor (target=release_debug, tools=yes)

    steps:
      - uses: actions/checkout@v2

      # Upload cache on completion and check it out now
      # Editing this is pretty dangerous for windows since it can break and needs properly tested with a fresh cache.
      # Linux with this will work reliably, so not as bad to edit for Linux.
      - name: Load .scons_cache directory
        id: macos-editor-cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{runner.os}}-editor-${{github.sha}}
          restore-keys: |
            ${{runner.os}}-editor-${{github.sha}}
            ${{runner.os}}-editor
            ${{runner.os}}

      # Use python 3.x release (works cross platform; best to keep self contained in it's own step)
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      # Setup scons, print python version and scons version info, so if anything is broken it won't run the build.
      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      # We should always be explicit with our flags usage here since it's gonna be sure to always set those flags
      - name: Compilation
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
        run: |
          scons -j2 verbose=yes warnings=all werror=yes platform=osx tools=yes target=release_debug

  macos-template:
    runs-on: "macos-latest"
    name: Template (target=release, tools=no)

    steps:
      - uses: actions/checkout@v2

      # Upload cache on completion and check it out now
      # Editing this is pretty dangerous for windows since it can break and needs properly tested with a fresh cache.
      # Linux with this will work reliably, so not as bad to edit for Linux.
      - name: Load .scons_cache directory
        id: macos-template-cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{runner.os}}-template-${{github.sha}}
          restore-keys: |
            ${{runner.os}}-template-${{github.sha}}
            ${{runner.os}}-template
            ${{runner.os}}

      # Use python 3.x release (works cross platform)
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      # You can test your matrix by printing the current Python version
      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version
      - name: Compilation
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
        run: |
          scons -j2 verbose=yes warnings=all werror=yes platform=osx target=release tools=no
